from datetime import datetime
from io import BytesIO
from xml.sax.saxutils import escape as esc

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

TEAL = colors.HexColor("#0B6E6A")
LEVEL = {"emergency": "#C23B2A", "urgent": "#C9740F", "moderate": "#9A7B0A", "mild": "#2E7D4F"}


def build_pdf(res):
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
                            title="Apna Hospital symptom report")
    ss = getSampleStyleSheet()
    H1 = ParagraphStyle("h1", parent=ss["Title"], textColor=TEAL, fontSize=22, alignment=0, spaceAfter=2)
    H2 = ParagraphStyle("h2", parent=ss["Heading2"], textColor=TEAL, fontSize=13, spaceBefore=10, spaceAfter=4)
    P = ParagraphStyle("p", parent=ss["BodyText"], fontSize=10, leading=14)
    SM = ParagraphStyle("sm", parent=P, fontSize=8, textColor=colors.grey)
    tri, top = res["triage"], res["results"][0]
    col = colors.HexColor(LEVEL[tri["level"]])
    s = [Paragraph("Apna Hospital", H1), Paragraph("AI symptom triage report · " + datetime.now().strftime("%d %b %Y, %H:%M"), SM), Spacer(1, 8)]
    box = Table([[Paragraph(f"<b>{esc(tri['title'])}</b><br/>{esc(tri['message'])}", ParagraphStyle("b", parent=P, textColor=colors.white))]], colWidths=[174 * mm])
    box.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), col), ("LEFTPADDING", (0, 0), (-1, -1), 10), ("TOPPADDING", (0, 0), (-1, -1), 8), ("BOTTOMPADDING", (0, 0), (-1, -1), 8)]))
    s += [box, Paragraph("Reported symptoms", H2), Paragraph(", ".join(esc(x["label"]) for x in res["symptoms"]), P),
          Paragraph("Possible conditions", H2)]
    rows = [["Condition", "Match likelihood", "See"]] + [[r["name"], f"{round(r['probability'] * 100)}%", r["specialist"]] for r in res["results"]]
    t = Table(rows, colWidths=[70 * mm, 36 * mm, 68 * mm])
    t.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), TEAL), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("FONTSIZE", (0, 0), (-1, -1), 9),
                           ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CBD8D4")), ("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
    s += [t, Paragraph(esc(top["name"]), H2), Paragraph(esc(top["description"]), P)]
    for title, k in [("Precautions", "precautions"), ("Commonly used treatments (discuss with a doctor)", "medications"), ("Diet", "diet"), ("Lifestyle", "lifestyle")]:
        if top.get(k):
            s.append(Paragraph(title, H2))
            s += [Paragraph("• " + esc(i), P) for i in top[k][:6]]
    s += [Spacer(1, 14), Paragraph("This report is generated by a machine-learning model trained on a public educational dataset. It is NOT a medical diagnosis and does not replace a "
                                    "qualified clinician. In an emergency call 112 (108 for ambulance, India).", SM)]
    doc.build(s)
    return buf.getvalue()
